[workspace]
members = [
    "crates/evm-prover",
    "crates/sp1/evm-exec/program",
    "crates/sp1/evm-exec/script",
    "crates/sp1/evm-exec-types",
    "crates/sp1/evm-range-exec/program",
    "crates/sp1/evm-range-exec/script",
]
resolver = "2"

[workspace.dependencies]
alloy-provider = { version = "0.12.6" }
alloy-sol-types = { version = "0.8.0", default-features = false }
base64 = "0.22.1"
bincode = "1.3.3"
celestia-rpc = "0.11"
celestia-types = "0.11"
eq-common = "0.1.4"
ethers = { version = "2.0", features = ["ws", "rustls"] }
hex = "0.4.3"
nmt-rs = "*"
reqwest = "0.12.20"
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.3", default-features = false }
reth-primitives = { git = "https://github.com/sp1-patches/reth", tag = "rsp-20240830", default-features = false, features = [
    "alloy-compat",
    "optimism",
    "std",
] }
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp.git", rev = "837a8c04a29deadb576a75fcf56136f26ce5dd4d" }
rsp-host-executor = { git = "https://github.com/succinctlabs/rsp.git", rev = "837a8c04a29deadb576a75fcf56136f26ce5dd4d" }
rsp-primitives = { git = "https://github.com/succinctlabs/rsp.git", rev = "837a8c04a29deadb576a75fcf56136f26ce5dd4d" }
rsp-rpc-db = { git = "https://github.com/succinctlabs/rsp.git", rev = "837a8c04a29deadb576a75fcf56136f26ce5dd4d" }
serde = "1.0"
serde_cbor = "0.11.2"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sha3 = "0.10"
sp1-build = "=4.1.4"
sp1-sdk = "=4.1.4"
sp1-zkvm = "=4.1.4"
tendermint = "0.40.1"
tendermint-proto = "*"
