[workspace]
members = [
    "crates/evm-prover",
    "crates/sp1/evm-exec",
    "crates/sp1/evm-exec-types",
]
resolver = "3"

[workspace.dependencies]
alloy-sol-types = { version = "0.8.0", default-features = false }
reth-primitives = { git = "https://github.com/sp1-patches/reth", tag = "rsp-20240830", default-features = false, features = [
    "alloy-compat",
    "optimism",
    "std",
] }
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp.git", rev = "837a8c04a29deadb576a75fcf56136f26ce5dd4d" }
tendermint = "0.40.1"
tendermint-proto = "*"
celestia-types = "0.10"
sha3 = "0.10"
eq-common = "0.1.4"
bincode = "1.3.3"
