services:
  celestia-init:
    image: ghcr.io/celestiaorg/celestia-app-standalone:feature-zk-execution-ism
    container_name: celestia-init
    entrypoint: /scripts/init.sh
    volumes:
      - ./scripts/init-celestia.sh:/scripts/init.sh:ro
      - celestia-app:/home/celestia/.celestia-app
    restart: "no"

  celestia-validator:
    image: ghcr.io/celestiaorg/celestia-app-standalone:feature-zk-execution-ism
    container_name: celestia-validator
    ports:
      - "26656:26656"
      - "26657:26657"
      - "9090:9090"
    healthcheck:
      test: [
        "CMD-SHELL",
        "bh=$(curl -sf http://localhost:26657/status | jq -r '.result.sync_info.latest_block_height'); if [ \"$$bh\" -gt 1 ]; then exit 0; else exit 1; fi"
      ]
      interval: 30s
      timeout: 5s
      start_period: 10s
    volumes:
      - celestia-app:/home/celestia/.celestia-app
    command: >
      start --force-no-bbr
    depends_on:
      celestia-init:
        condition: service_completed_successfully
    networks:
      - celestia-zkevm-net

  celestia-bridge:
    image: ghcr.io/celestiaorg/celestia-node:v0.23.0-rc0
    container_name: celestia-bridge
    volumes:
      - ./scripts/init-celestia-bridge.sh:/scripts/init.sh:ro
      - celestia-bridge:/home/celestia
    entrypoint: /scripts/init.sh
    command: celestia bridge start --log.level.module share/discovery:fatal --keyring.keyname node --rpc.skip-auth
    ports:
      - "26658:26658"
      - "2121:2121"
    healthcheck:
      test: >
        curl -sf -X POST http://localhost:26658
        -H "Content-Type: application/json"
        -d '{"id":1,"jsonrpc":"2.0","method":"node.Ready","params":[]}' | grep true
      interval: 10s
      start_period: 10s
    depends_on:
      celestia-validator:
        condition: service_healthy
    networks:
      - celestia-zkevm-net

volumes:
  celestia-app:
  celestia-bridge:

networks:
  celestia-zkevm-net:
    driver: bridge