# yaml-language-server: $schema=https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/v15.2.0/deployments/warp_routes/schema.json
tokens:
  - addressOrDenom: "0x8ccBa74d0010B76F3E9507bb3A86cC394F96815d"
    chainName: rethlocal
    decimals: 6
    name: SynTIA
    standard: EvmHypSynthetic
    symbol: TIA
