# yaml-language-server: $schema=https://raw.githubusercontent.com/hyperlane-xyz/hyperlane-registry/v15.2.0/deployments/warp_routes/schema.json
tokens:
  - addressOrDenom: "0x032e1B988eB5Ac8F0C8617E09de92a664cABf37D"
    chainName: rethlocal
    decimals: 6
    name: SynTIA
    standard: EvmHypSynthetic
    symbol: TIA
