name: Rust CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          components: rustfmt
          toolchain: 1.85.0
      - run: cargo fmt --all -- --check

  clippy:
    name: Lint with Clippy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          components: clippy
          toolchain: 1.85.0
      - run: cargo clippy --workspace --all-targets --release --locked -- -D warnings

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          toolchain: 1.85.0

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Build Rust programs
        run: |
          cargo build --release --locked

  run:
    name: Execute SP1 programs
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          toolchain: 1.85.0
      
      - name: Execute SP1 Block execution
        run: |
          for dir in ./testdata/inputs/block-*; do
            # Extract block number from directory name (e.g. block-15)
            name=$(basename "$dir") 
            block_number=${name#block-}
            
            echo "Running SP1 block execution program for $block_number"
            cargo run -p evm-exec-script --bin evm-exec --release --locked -- --execute --height $block_number
          done

      - name: Execute SP1 Block range execution
        run: |
          echo "Running SP1 block range execution program"
          cargo run -p evm-range-exec-script --bin evm-range-exec --release --locked -- --execute
