name: Build Rust

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-run:
    name: Build and Execute
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.85.0

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Build Rust programs
        run: |
          cargo build --release
